trigger:
- master

pool:
  vmImage: 'win1803'

variables:
- group: 'AzureConnections'

steps:
- task: AzureFileCopy@2
  displayName: 'AzureBlob File Copy'
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)'
    azureSubscription: '$(Subscription)'
    Destination: AzureBlob
    storage: $(StorageName)
    ContainerName: '$web'
