trigger:
- master

pool:
  vmImage: 'win1803'

variables:
- group: 'AzureConnections'

steps:
- task: AzureFileCopy@3
  inputs:
    SourcePath: '.'
    azureSubscription: 'Pay-As-You-Go (455c1742-6ea0-4579-b84a-0d9bc1de2139)'
    Destination: 'AzureBlob'
    storage: 'dn1simplesitestorage'
    ContainerName: '$web'